name: zeth-ci

on:
  push:
  pull_request:

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp"
  CI_EVENT_NAME: ${{ github.event_name }}

jobs:

  check-contracts:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Check Contracts
      run: CI_USE_DOCKER=1 scripts/ci contracts_check

  check-pyclient:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_USE_DOCKER=1 scripts/ci pyclient_check

  build-macos-debug:
    runs-on: macos-10.15
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Dependencies
      run: brew install ${MACOS_BREW_PACKAGES}
    - name: Execute
      run: CI_CONFIG=${{ matrix.config }} scripts/ci build

  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_CHECK_FORMAT=1 CI_USE_DOCKER=1 CI_CONFIG=${{ matrix.config }} scripts/ci build

  build-linux-pghr13:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_USE_DOCKER=1 CI_CONFIG=Release CI_ZKSNARK=PGHR13 scripts/ci build
