# Actions for every push
name: zeth-ci-push

on:
  push:

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp"

jobs:

  check-contracts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Check Contracts
      run: CI_USE_DOCKER=1 scripts/ci check_contracts

  check-client:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: scripts/ci check_client

  build-macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Dependencies
      run: brew install ${MACOS_BREW_PACKAGES}
    - name: Execute
      run: CI_CONFIG=${{ matrix.config }} scripts/ci build

  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_CHECK_FORMAT=1 CI_USE_DOCKER=1 CI_CONFIG=${{ matrix.config }} scripts/ci build

  build-linux-pghr13:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_USE_DOCKER=1 CI_CONFIG=Release CI_ZKSNARK=PGHR13 scripts/ci build

  check-cpp-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Execute
      run: CI_CHECK_FORMAT=1 CI_USE_DOCKER=1 scripts/ci check_cpp
